"""Exact fast path for the verified matched linear sticking sphere/plane law.

A conditional closed-form material solver, not a generic rigid-body friction
rule: it rejects damping, unequal mode frequencies, existing elastic memory,
plastic yielding, nonzero gravity during contact and the weighted material.
"""
from dataclasses import dataclass
import numpy as np
from research.elastic_patch import Material


class UnsupportedImpact(ValueError):
    """Caller must use a resolved material integration for this contact."""


def vector(value,name):
    result=np.asarray(value,dtype=float)
    if result.shape!=(3,) or not np.all(np.isfinite(result)):
        raise ValueError(name+' must be a finite three-vector')
    return result


@dataclass(frozen=True)
class Impact:
    material: Material
    normal: np.ndarray
    incoming_velocity: np.ndarray
    incoming_omega: np.ndarray
    linear_impulse: np.ndarray
    independent_angular_impulse: np.ndarray
    outgoing_velocity: np.ndarray
    outgoing_omega: np.ndarray
    duration_s: float
    required_friction: float
    peak_compression_m: float
    energy_residual_J: float

    def trajectory(self,times,position=(0.,0.,.1)):
        """Exact COM/velocities and contact stores; sphere orientation omitted."""
        time=np.asarray(times,dtype=float)
        if time.ndim!=1 or not np.all(np.isfinite(time)) or np.any(time<0) or np.any(time>self.duration_s+1e-14):
            raise ValueError('times must lie in the contact interval')
        pos=vector(position,'position'); m=self.material
        frequency=np.pi/self.duration_s; sine=np.sin(frequency*time)
        factor=.5*(1-np.cos(frequency*time)); half=.5*self.linear_impulse
        omega_half=.5*(np.cross(-m.radius*self.normal,self.linear_impulse)+self.independent_angular_impulse)/m.inertia
        velocity=self.incoming_velocity+factor[:,None]*self.linear_impulse/m.mass
        omega=self.incoming_omega+2*factor[:,None]*omega_half
        position=pos+time[:,None]*self.incoming_velocity+(time-sine/frequency)[:,None]*half/m.mass
        u=self.incoming_velocity+np.cross(self.incoming_omega,-m.radius*self.normal)
        u-=self.normal*(self.normal@u); spin=self.normal@self.incoming_omega
        effective_mass=1/(1/m.mass+m.radius**2/m.inertia)
        Un=-self.normal@self.incoming_velocity
        normal_store=.5*m.mass*Un**2*sine**2
        tangent_store=.5*effective_mass*np.dot(u,u)*sine**2
        twist_store=.5*m.inertia*spin**2*sine**2
        kinetic=.5*m.mass*np.sum(velocity**2,axis=1)+.5*m.inertia*np.sum(omega**2,axis=1)
        force=.5*frequency*sine[:,None]*self.linear_impulse
        couple=.5*frequency*sine[:,None]*self.independent_angular_impulse
        return dict(times=time,position=position,velocity=velocity,omega=omega,
                    normal_stored_J=normal_store,tangent_stored_J=tangent_store,
                    twist_stored_J=twist_store,kinetic_J=kinetic,force_N=force,
                    independent_couple_N_m=couple)


def impact(material,normal,velocity,omega,*,gravity=(0.,0.,0.),
           history=(0.,0.,0.),max_compression_fraction=.25):
    """Resolve only when the material and instantaneous force bound prove stick.

    The vector ``history`` is [q1,q2,a*theta]. The exact shared force/couple
    criterion holds at *every* contact instant, since the three elastic modes
    share one half-sine force profile. The output couple is independent of the
    angular impulse generated by the contact lever arm.
    """
    m=material; n=vector(normal,'normal'); v=vector(velocity,'velocity'); w=vector(omega,'omega')
    if not np.isclose(np.linalg.norm(n),1.,rtol=0,atol=1e-12): raise ValueError('normal must be unit length')
    if not np.isfinite(max_compression_fraction) or not 0<max_compression_fraction<=.5:
        raise ValueError('max_compression_fraction must lie in (0,.5]')
    if np.any(vector(gravity,'gravity')) or np.any(vector(history,'history')):
        raise UnsupportedImpact('gravity or prior history requires material integration')
    if m.compression_exponent!=0 or m.normal_damping!=0:
        raise UnsupportedImpact('weighted contact or damping requires material integration')
    frequency=np.sqrt(m.normal_stiffness/m.mass)
    effective_mass=1/(1/m.mass+m.radius**2/m.inertia)
    if not np.isclose(m.tangent_stiffness,effective_mass*frequency**2,rtol=1e-12,atol=1e-12) or not np.isclose(m.twist_stiffness,m.inertia*frequency**2,rtol=1e-12,atol=1e-12):
        raise UnsupportedImpact('contact mode frequencies do not match')
    Un=-n@v
    if Un<=0: raise UnsupportedImpact('contact is not approaching')
    compression=Un/frequency
    if compression>max_compression_fraction*m.radius:
        raise UnsupportedImpact('compression exceeds declared sphere approximation budget')
    r=-m.radius*n
    u=v+np.cross(w,r);u-=n*(n@u)
    spin=n@w
    required=np.hypot(effective_mass*np.linalg.norm(u),m.inertia*spin/m.effective_length)/(m.mass*Un)
    if required>m.friction*(1+1e-12):
        raise UnsupportedImpact('shared force/couple capacity predicts yielding')
    P=2*m.mass*Un*n-2*effective_mass*u
    L=-2*m.inertia*spin*n
    vp=v+P/m.mass;wp=w+(np.cross(r,P)+L)/m.inertia
    before=.5*m.mass*np.dot(v,v)+.5*m.inertia*np.dot(w,w)
    after=.5*m.mass*np.dot(vp,vp)+.5*m.inertia*np.dot(wp,wp)
    if not np.isfinite(after) or abs(after-before)>1e-12*max(1.,before):
        raise UnsupportedImpact('floating-point energy gate failed')
    return Impact(m,n,v,w,P,L,vp,wp,np.pi/frequency,float(required),float(compression),float(after-before))


def resolve_impact(material,normal,velocity,omega,*,gravity=(0.,0.,0.),
                   history=(0.,0.,0.),max_compression_fraction=.25,
                   rtol=1e-11,atol=1e-13,max_rhs_evaluations=200000,
                   energy_absolute_J=1e-8,energy_relative=1e-9,
                   yield_absolute_N=1e-5,yield_relative=1e-8):
    """Choose computational effort inside the SAME sphere/plane material.

    Use the exact matched-mode branch only when its instantaneous force budget
    proves sticking. Otherwise integrate the configured elastic/plastic law.
    This dispatcher supports one fixed plane, initially touching sphere, zero
    pre-existing history and zero gravity during contact. It is not a world
    integrator, a multiple-contact solver or a rubber parameter calibration.
    """
    from research.elastic_patch import Plane,simulate
    m=material;n=vector(normal,'normal');v=vector(velocity,'velocity');w=vector(omega,'omega')
    if np.any(vector(gravity,'gravity')) or np.any(vector(history,'history')):
        raise UnsupportedImpact('dispatcher currently supports zero gravity and zero prior history')
    if -n@v<=0: raise UnsupportedImpact('contact is not approaching')
    try:
        exact=impact(m,n,v,w,max_compression_fraction=max_compression_fraction)
        return dict(method='exact-matched-elastic',velocity=exact.outgoing_velocity,
                    omega=exact.outgoing_omega,linear_impulse_N_s=exact.linear_impulse,
                    independent_couple_impulse_N_m_s=exact.independent_angular_impulse,
                    contact_duration_s=exact.duration_s,compression_upper_bound_m=exact.peak_compression_m,dissipated_J=0.,
                    energy_residual_J=exact.energy_residual_J,exact=exact)
    except UnsupportedImpact as rejection:
        reason=str(rejection)
    # All forces in this material have Fn >= kn*delta. For one fixed plane
    # without gravity, first lift-off occurs no later than the normal spring's
    # half period. The extra 1% safely covers finite numerical event error.
    half_period=np.pi*np.sqrt(m.mass/m.normal_stiffness)
    numerical=simulate(m,position=m.radius*n,velocity=v,omega=w,planes=(Plane(tuple(n)),),
                       duration=1.01*half_period,sample_dt=half_period/200,
                       max_step=half_period/200,rtol=rtol,atol=atol,
                       max_rhs_evaluations=max_rhs_evaluations)
    lifts=[e for e in numerical['events'] if e['kind']=='lift_off']
    if len(lifts)!=1: raise UnsupportedImpact('resolved contact has no unique lift-off within its budget')
    before=float(numerical['kinetic_J'][0]+numerical['stored_J'][0])
    residual=float(np.max(abs(numerical['energy_residual_J'])))
    # Passivity and nonnegative channel stores bound the normal spring energy
    # by the complete initial energy, including rotation. This conservative
    # deformation check does not miss a peak between presentation samples.
    compression_bound=np.sqrt(2*max(0.,before+residual)/m.normal_stiffness)
    if compression_bound>max_compression_fraction*m.radius:
        raise UnsupportedImpact('energy-based compression bound exceeds the sphere approximation budget')
    if residual>energy_absolute_J+energy_relative*before:
        raise UnsupportedImpact('resolved contact failed its complete energy gate')
    load_peak=float(np.max(numerical['normal_force_N']))
    if numerical['max_yield_excess_N']>yield_absolute_N+yield_relative*load_peak:
        raise UnsupportedImpact('resolved contact failed its shared force/couple yield gate')
    if np.min(np.diff(numerical['dissipated_J']))<-energy_absolute_J or numerical['dissipated_J'][-1]<-energy_absolute_J:
        raise UnsupportedImpact('resolved contact produced negative dissipation')
    event=lifts[0]
    return dict(method='resolved-compliant',exact_rejection=reason,
                velocity=np.asarray(event['velocity_m_s']),omega=np.asarray(event['omega_rad_s']),
                linear_impulse_N_s=np.asarray(event['linear_impulse_N_s']),
                independent_couple_impulse_N_m_s=np.asarray(event['couple_impulse_N_m_s']),
                contact_duration_s=event['time_s'],compression_upper_bound_m=float(compression_bound),dissipated_J=float(numerical['dissipated_J'][-1]),
                energy_residual_J=residual,trajectory=numerical)
