import ast,hashlib,json,subprocess
from pathlib import Path
import numpy as np
ROOT=Path.cwd();D=ROOT/'research/mixed-face-native/integration';load=lambda p:json.loads(Path(p).read_text());save=lambda p,x:Path(p).write_text(json.dumps(x,indent=2,allow_nan=False)+'\n');sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
fn=next(n for n in ast.parse((ROOT/'research/new-combined-contact-review/run-20261005T194211Z/run23.py').read_text()).body if isinstance(n,ast.FunctionDef) and n.name=='external');ns={'np':np};exec(compile(ast.Module(body=[fn],type_ignores=[]),'independent','exec'),ns)
old=load('research/component-cap192/live23/receipt.json');cases=old['records'];T=D/'live23';T.mkdir(exist_ok=False);records=[];exe=ROOT/'build/spatial/spatial_coulomb_replay';guards={str(p):sha(p) for p in [exe,ROOT/'spatial_engine.py',*[p for p in (ROOT/'spatial_backend').glob('*') if p.is_file()]]}
for i,case in enumerate(cases):
 inp=ROOT/case['input'];assert sha(inp)==case['input_sha256'];data=load(inp);r=subprocess.run([str(exe),str(inp)],capture_output=True,text=True);(T/f'{i:02d}.stdout.json').write_text(r.stdout);(T/f'{i:02d}.stderr').write_text(r.stderr);o=json.loads(r.stdout);gate=ns['external'](data,o);before=load(ROOT/f'research/component-cap192/live23/{i:02d}.stdout.json');exact=np.asarray(o['p']).tobytes()==np.asarray(before['p']).tobytes() and np.asarray(o['w']).tobytes()==np.asarray(before['w']).tobytes() and o['stats']==before['stats'];assert r.returncode==0 and o['accepted'] and gate['accepted'] and exact and o['mobility_continuation_policy']['attempts']==0 and o['terminal_component_polish_policy']['attempts']==0 and o['mixed_face_traction_policy']['attempts']==0;records.append({'input':case['input'],'old_endpoint_bytes_and_counters_exact':exact,'original_physics_passed':True,'new_helper_bypassed':True});print('old',i,'exact',exact,flush=True)
save(T/'receipt.json',{'passed':True,'guards':guards,'records':records});inputs=list(load(ROOT/'research/mobility-continuation/plan.json')['inputs']);inputs+=['research/large-velocity-cap128-world/results/trial_0/rejection.json','research/large-mobility-world/results/hull125_h10us/rejection.json','research/large-mobility-world/results/hull125_h5us/rejection.json','research/large-mobility-world/results/hull64_h10us/rejection.json'];inputs+=['research/large-terminal-world/results/hull125_h10us/rejection.json','research/large-terminal-world/results/hull125_h5us/rejection.json'];actual=[]
for i,path in enumerate(inputs):
 r=subprocess.run([str(exe),str(ROOT/path)],capture_output=True,text=True);(D/f'actual_{i}.stdout.json').write_text(r.stdout);(D/f'actual_{i}.stderr').write_text(r.stderr);o=json.loads(r.stdout);gate=ns['external'](load(ROOT/path),o);assert not o['accepted'] or gate['accepted'];actual.append({'input':path,'accepted':bool(o['accepted'] and gate['accepted'] and r.returncode==0),'native_exit':r.returncode,'independent':gate,'mobility_policy':o['mobility_continuation_policy'],'reduced_policy':o['reduced_mobility_policy'],'mixed_face_policy':o['mixed_face_traction_policy']});print('actual',i,actual[-1]['accepted'],gate['projection_m_s'],o['mobility_continuation_policy'],flush=True);save(D/'actual-progress.json',actual)
assert all(sha(p)==v for p,v in guards.items());save(D/'actual-receipt.json',{'passed':all(r['accepted'] for r in actual[:8]) and not any(r['accepted'] for r in actual[8:]),'guards':guards,'records':actual,'scope':'Eight actual original-law proofs and two retained later declines; no world/performance qualification.'})
