"""Isolated exact prescribed-pose clock; freeze production sources unchanged."""
import hashlib,json,shutil,subprocess
from pathlib import Path
H=Path(__file__).resolve().parent;ROOT=H.parents[1];D=H/'build-results';D.mkdir(exist_ok=False);C=Path('/home/viktor/.cache/physics-spatial-analytic-clock-20261006');C.mkdir(exist_ok=False);src=C/'source';shutil.copytree(ROOT/'spatial_backend',src);sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();original={str(p):sha(p) for p in (ROOT/'spatial_backend').glob('*') if p.is_file()};p=src/'runner.cpp';s=p.read_text().replace('#include <cstdio>','#include <cstdio>\n#include <cstdlib>')
needle=' json states=json::array(),times=json::array(),updates=json::array();'
insert=''' struct InitialMotion {btVector3 pos,v,w;btQuaternion q;json schedule;};
 std::vector<InitialMotion> initial;for(const auto& b:bodies)initial.push_back({b.pos,b.v,b.w,b.q,b.schedule});
 auto analytic_pose=[&](size_t index,double target){
  auto& b=bodies[index];const auto& origin=initial[index];auto pos=origin.pos;auto q=origin.q;auto v=origin.v;auto w=origin.w;double at=0;
  auto advance=[&](double delta){pos+=v*delta;double speed=w.length();if(speed>0){q=btQuaternion(w/speed,speed*delta)*q;q.normalize();}};
  for(const auto& cmd:origin.schedule){double event=cmd.at("time_s").get<double>();if(event>target)break;advance(event-at);at=event;v=vec(cmd.at("velocity"));w=vec(cmd.at("omega"));}
  advance(target-at);b.rb->setInterpolationWorldTransform(b.rb->getWorldTransform());b.pos=pos;b.q=q;b.rb->setWorldTransform(btTransform(q,pos));b.rb->setLinearVelocity(b.v);b.rb->setAngularVelocity(b.w);world.updateSingleAabb(b.rb.get());
 };
''';assert s.count(needle)==1;s=s.replace(needle,insert+needle)
needle=' int frames=in.at("frames"),primary=in.at("primary_steps"),total=0;';insert='''
 const bool analytic=std::getenv("PHYSICS_DISABLE_ANALYTIC_CLOCK")==nullptr;
 if(analytic){if(fraction!=0)throw std::runtime_error("Analytic-clock prototype requires fixed primary stepping");for(const auto& b:bodies)if(b.kin)for(const auto& cmd:b.schedule){double index=cmd.at("time_s").get<double>()/dt;if(std::abs(index-std::round(index))>1e-10)throw std::runtime_error("Prototype schedule event must align to output frame");}}
''';assert s.count(needle)==1;s=s.replace(needle,needle+insert)
s=s.replace('while(left>dt*1e-12){','while(analytic?count<primary:left>dt*1e-12){').replace('double t=(f+1)*dt-left, speed=0;','double t=analytic?dt*(f+double(count)/primary):(f+1)*dt-left, speed=0;').replace('double h=std::min(left,dt/primary);','double h=analytic?dt/primary:std::min(left,dt/primary);').replace('for(auto& b:bodies)if(b.kin)for(const auto& cmd:b.schedule){double event=','if(!analytic)for(auto& b:bodies)if(b.kin)for(const auto& cmd:b.schedule){double event=')
old='for(auto& b:bodies)if(b.kin){b.rb->setInterpolationWorldTransform(b.rb->getWorldTransform());b.pos+=b.v*h; double w=b.w.length();if(w>0){b.q=btQuaternion(b.w/w,w*h)*b.q;b.q.normalize();}b.rb->setWorldTransform(btTransform(b.q,b.pos));b.rb->setLinearVelocity(b.v);b.rb->setAngularVelocity(b.w);world.updateSingleAabb(b.rb.get());}'
assert s.count(old)==2;s=s.replace(old,'if(analytic){for(size_t i=0;i<bodies.size();i++)if(bodies[i].kin)analytic_pose(i,dt*(f+double(count)/primary));}else{'+old+'}')
s=s.replace('progress["terminal_component_polish_policy"]=terminal_polish_policy();','progress["terminal_component_polish_policy"]=terminal_polish_policy();\n  progress["analytic_clock_policy"]={{"enabled",analytic},{"fixed_integer_phase",true},{"pose","original initial COM pose plus exact piecewise constant authored velocity/quaternion exponentials"},{"production_adoption",false}};').replace('out["terminal_component_polish_policy"]=terminal_polish_policy();','out["terminal_component_polish_policy"]=terminal_polish_policy();\n out["analytic_clock_policy"]={{"enabled",analytic},{"fixed_integer_phase",true},{"pose","original initial COM pose plus exact piecewise constant authored velocity/quaternion exponentials"},{"production_adoption",false}};');p.write_text(s)
cache={}
for line in (ROOT/'build/spatial/CMakeCache.txt').read_text().splitlines():
 if '=' in line and ':' in line:cache[line.split(':')[0]]=line.split('=',1)[1]
lib=ROOT/'build/spatial/_deps/bullet-build/src';exe=C/'spatial_runner';command=['c++','-std=c++17','-O3','-DNDEBUG','-DBT_USE_DOUBLE_PRECISION','-DSPATIAL_LAPACK_RECOVERY=1','-ffp-contract=off','-I'+str(src),'-I'+str(Path(cache['BULLET_PHYSICS_SOURCE_DIR'])/'src'),'-I'+str(Path(cache['nlohmann_json_SOURCE_DIR'])/'include'),str(p),'-o',str(exe),str(lib/'BulletDynamics/libBulletDynamics.a'),str(lib/'BulletCollision/libBulletCollision.a'),str(lib/'LinearMath/libLinearMath.a'),'-l:liblapack.so.3','-l:libblas.so.3'];r=subprocess.run(command,capture_output=True,text=True);(D/'compile.stdout').write_text(r.stdout);(D/'compile.stderr').write_text(r.stderr);save=lambda p,d:p.write_text(json.dumps(d,indent=2)+'\n');save(D/'compile.json',{'command':command,'exit':r.returncode});r.check_returncode();assert all(sha(p)==v for p,v in original.items());save(H/'build-receipt.json',{'source':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),'original_guards':original,'transformed':{str(p):sha(p) for p in src.glob('*') if p.is_file()},'binary':str(exe),'binary_sha256':sha(exe),'builder_sha256':sha(Path(__file__)),'scope':'Isolated prescribed-pose/clock diagnostic; every contact/position equation and gate unchanged.'})
