"""Bounded native comparator; preserve compilation, real declines, original gate."""
import ast,hashlib,json,os,re,subprocess,time
from pathlib import Path
import numpy as np
H=Path(__file__).resolve().parent;ROOT=H.parents[1];D=H/'native-results';D.mkdir(exist_ok=False);plan=json.loads((H/'plan.json').read_text());save=lambda p,x:p.write_text(json.dumps(x,indent=2,allow_nan=False)+'\n');sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
assert os.environ['OMP_NUM_THREADS']=='1' and os.environ['OPENBLAS_NUM_THREADS']=='1'
cache={}
for line in (ROOT/'build/spatial/CMakeCache.txt').read_text().splitlines():
 if '=' in line and ':' in line:cache[line.split(':')[0]]=line.split('=',1)[1]
bullet=Path(cache['BULLET_PHYSICS_SOURCE_DIR']);js=Path(cache['nlohmann_json_SOURCE_DIR']);lib=ROOT/'build/spatial/_deps/bullet-build/src';exe=Path('/home/viktor/.cache/physics-reduced-support-all-20261006');assert not exe.exists()
paths=[Path(__file__),H/'plan.json',H/'native_helper.h',H/'native_replay.cpp',*[p for p in (ROOT/'spatial_backend').glob('*') if p.is_file()]];guards={str(p):sha(p) for p in paths};command=['c++','-std=c++17','-O3','-DNDEBUG','-DBT_USE_DOUBLE_PRECISION','-DSPATIAL_LAPACK_RECOVERY=1','-ffp-contract=off','-I'+str(ROOT/'spatial_backend'),'-I'+str(bullet/'src'),'-I'+str(js/'include'),str(H/'native_replay.cpp'),'-o',str(exe),str(lib/'BulletDynamics/libBulletDynamics.a'),str(lib/'BulletCollision/libBulletCollision.a'),str(lib/'LinearMath/libLinearMath.a'),'-l:liblapack.so.3','-l:libblas.so.3'];r=subprocess.run(command,capture_output=True,text=True);(D/'compile.stdout').write_text(r.stdout);(D/'compile.stderr').write_text(r.stderr);save(D/'compile.json',{'command':command,'exit':r.returncode});r.check_returncode()
libs=re.findall(r'(/\S+)\s+\(',subprocess.check_output(['ldd',str(exe)],text=True));save(D/'provenance.json',{'source':subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),'guards':guards,'compiler':subprocess.check_output(['c++','--version'],text=True),'binary_path':str(exe),'binary_sha256':sha(exe),'runtime':{str(Path(p).resolve()):sha(Path(p).resolve()) for p in libs}})
fn=next(n for n in ast.parse((ROOT/'research/new-combined-contact-review/run-20261005T194211Z/run23.py').read_text()).body if isinstance(n,ast.FunctionDef) and n.name=='external');ns={'np':np};exec(compile(ast.Module(body=[fn],type_ignores=[]),'independent','exec'),ns);records=[]
for i,(path,digest) in enumerate(plan['inputs'].items()):
 assert sha(ROOT/path)==digest;data=json.loads((ROOT/path).read_text());start=time.perf_counter();r=subprocess.run([str(exe),str(ROOT/path)],capture_output=True,text=True);(D/f'{i}.stdout.json').write_text(r.stdout);(D/f'{i}.stderr').write_text(r.stderr);o=json.loads(r.stdout);gate=ns['external'](data,o);assert r.returncode in [0,2];assert not o['accepted'] or gate['accepted'];record={'input':path,'accepted':bool(o['accepted'] and gate['accepted']),'exit':r.returncode,'independent':gate,'policy':o['mobility_continuation_policy'],'elapsed_s_descriptive':time.perf_counter()-start};records.append(record);save(D/'progress.json',records);print(len(data['b']),'native original accepted',record['accepted'],gate['projection_m_s'],flush=True)
assert all(sha(p)==v for p,v in guards.items());save(D/'summary.json',{'complete':True,'guards_unchanged':True,'records':records,'scope':'Instantaneous native research comparator only; all original gates, no world/performance qualification.'})
