"""Published profile table and fixed-input experimental reproduction figure."""
from pathlib import Path
import json,math,html,textwrap
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
P=Path(__file__).resolve().parent;catalog=json.loads((P/'catalog.json').read_text());summary=json.loads((P/'glass-worksheet-comparison/summary.json').read_text());profile=next(r for r in catalog['profiles'] if r['id']==summary['profile_id']);R=profile['sphere_diameter_m']/2
colors={'Capacity limited':'#6d5da8','Tangential target realized':'#208b83'};points=[]
for r in summary['records']:
 vtin=r['incoming_relative_tangent_m_s'];dvobs=r['source_tangent_center_after_m_s']-vtin;dvpred=r['native_tangent_center_after_m_s']-vtin
 # Pair COM frame; source spin is explicitly reconstructed, not measured.
 o=np.array([abs(r['source_normal_after_m_s'])/2,abs(r['source_tangent_center_after_m_s'])/2,abs(dvobs)/.8]);p=np.array([abs(r['native_normal_after_m_s'])/2,abs(r['native_tangent_center_after_m_s'])/2,abs(dvpred)/.8]);a=math.degrees(math.acos(np.clip(o@p/(np.linalg.norm(o)*np.linalg.norm(p)),-1,1)));e=100*(np.linalg.norm(p)/np.linalg.norm(o)-1)
 needed=(1+profile['tangential_restitution']['value'])*abs(vtin)/3.5;cap=profile['sliding_friction']['value']*(1+profile['normal_restitution']['value'])*abs(r['incoming_relative_normal_m_s']);kind='Capacity limited' if needed>cap else 'Tangential target realized'
 points.append({'id':f"Glass photo roll{r['roll']:g} frame{r['frame']:g}",'type':kind,'ell_m':R,'observed_signature':o.tolist(),'predicted_signature':p.tolist(),'mix_angle_error_deg':a,'magnitude_error_percent':e,'measured_comparison':'Source worksheet contact reconstruction; spin inferred by angular momentum, not independently measured. Published coefficients unchanged.','source_excel_row':r['source_excel_row']})
fig,ax=plt.subplots(figsize=(10,6.5))
for kind,color in colors.items():
 batch=[r for r in points if r['type']==kind];ax.scatter([r['mix_angle_error_deg'] for r in batch],[r['magnitude_error_percent'] for r in batch],s=68,facecolors='none',edgecolors=color,linewidths=1.4,label=f'{kind} ({len(batch)})')
ax.scatter([0],[0],marker='*',s=190,color='black',label='Exact agreement');ax.axhline(0,color='#777',linewidth=.8);ax.grid(alpha=.2);ax.set_axisbelow(True);ax.set_xlim(-.5,max(r['mix_angle_error_deg'] for r in points)*1.15);ax.set_xlabel('Velocity–spin mix error (degrees; signature space)');ax.set_ylabel('Combined signature magnitude error (%)');ax.set_title('Published material inputs, no project fitting\n24 glass–glass impacts from the original worksheet');ax.legend(frameon=False,fontsize=9)
fig.text(.1,.015,'Hollow points: source spin is reconstructed from angular momentum, not independently measured.\nThe profile and worksheet may share characterization trials; this is reproduction, not independent validation.',fontsize=8,color='#555');fig.tight_layout(rect=[0,.07,1,1]);fig.savefig(P/'material-backed-deviation-map.png',dpi=180);fig.savefig(P/'material-backed-deviation-map.pdf');plt.close(fig)
(P/'material-backed-deviation-map.json').write_text(json.dumps({'points':points,'profile_id':profile['id'],'fixed_parameters':summary['fixed_parameters'],'no_project_fitting':True,'independent_parameter_dataset':False,'source_spin_is_inferred':True},indent=2)+'\n')
# Reuse accessible standalone SVG inspection, preserving the reduced observation caveat.
old=P.parent/'scaled-contact-article/deviation-map.html';page=old.read_text();begin=page.index('const rows=');end=page.index(';const svg=',begin);page=page[:begin]+'const rows='+json.dumps(points)+', colors='+json.dumps(colors)+page[end:]
start=page.index('<p class="hint">');end=page.index('</p>',start)+4
page=page[:start]+'<p class="hint">24glass/glass records; fixed published en,et,mu. Observable signature is for one sphere in the pair COM frame, with ell equal to nominal radius. Normal/contact quantities come from the source worksheet; spin is inferred by angular-momentum balance under sphere inertia, not independently measured. Hollow static points mark that limitation. The parameter table and worksheet may share characterization data: no independent validation or universal material accuracy is claimed.</p>'+page[end:]
(P/'material-backed-deviation-map.html').write_text(page)
def coeff(r,k):
 p=r[k];return f"{p['value']:g} ± {p['reported_uncertainty']:g}"
rows=''.join('<tr><td>'+html.escape(r['id'])+'</td><td>'+html.escape(r['body_material']+' / '+r['other_material'])+'</td><td>'+html.escape(r['geometry'])+'</td><td>'+str(r['sphere_diameter_m']*1000)+'</td>'+''.join('<td>'+coeff(r,k)+'</td>' for k in ['normal_restitution','tangential_restitution','sliding_friction'])+'<td><a href="'+r['source_url']+'">Primary source</a></td></tr>' for r in catalog['profiles'])
page='<!doctype html><meta charset="utf-8"><title>Documented material-pair profiles</title><style>body{font:16px/1.5 system-ui;max-width:1200px;margin:30px auto;padding:15px}table{border-collapse:collapse;width:100%;font-size:14px}td,th{padding:8px;border-bottom:1px solid #ddd;text-align:left}</style><h1>Documented material-pair profiles</h1><p>All values below are published experimental characterization, not project-fitted coefficients. Select a specific specimen/surface/geometry profile, not a generic material name. Reported uncertainties are preserved; these are not universal exact constants.</p><table><tr><th>Profile ID</th><th>Pair</th><th>Geometry</th><th>Diameter mm</th><th>Normal restitution</th><th>Tangential restitution</th><th>Sliding friction</th><th>Source</th></tr>'+rows+'</table><h2>Untuned measured comparison</h2><p>24glass-binary worksheet impacts with published inputs unchanged: normal RMSE '+f"{summary['normal_rmse_m_s']:.5f}"+'m/s; tangential COM-relative RMSE '+f"{summary['center_tangent_rmse_m_s']:.5f}"+'m/s. Spin comes from the author angular-momentum reconstruction, not an independent vector measurement. The parameter chart and records may share original characterization trials.</p><p>81native analytic/energy checks pass. These verify integration, not experimental accuracy. Caltech air/Zerodur profiles specify normal speeds0.05–0.38m/s and12.7mm spheres; other summary-page context remains unknown.</p><h2>Unavailable requested profiles</h2><p>Limestone/C25concrete lacks a complete signed contact en/et/mu set in the reviewed source. Cross2010Superball surfaces lack matched independently specified sliding friction. Historical fitted rock values and assumed rubber mu are excluded from this catalog.</p><p><a href="material-backed-deviation-map.html">Inspect the24comparison points</a></p>'
(P/'catalog.html').write_text(page)
print('Catalog table and24point documented-input map built')
