"""Guarded actual rejection replays with cap128 and unchanged original gates."""
import ast,hashlib,json,os,subprocess,time
from pathlib import Path
import numpy as np
H=Path(__file__).resolve().parent;ROOT=H.parents[1];plan=json.loads((H/'plan.json').read_text());D=H/'results';D.mkdir(exist_ok=False)
def save(p,x):p.write_text(json.dumps(x,indent=2,allow_nan=False)+'\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert all(sha(H/p)==v for p,v in plan['source_guards'].items());assert os.environ['OMP_NUM_THREADS']=='1' and os.environ['OPENBLAS_NUM_THREADS']=='1'
exe=Path(plan['binary']);exe.parent.mkdir(exist_ok=False);base=ROOT/'build/spatial/_deps/bullet-build/src';command=['c++','-O3','-DNDEBUG','-DBT_USE_DOUBLE_PRECISION','-DSPATIAL_LAPACK_RECOVERY=1','-ffp-contract=off','-I'+str(ROOT/'spatial_backend'),'-I/home/viktor/.cache/physics-relation-20261005/deps/_deps/bullet-src/src','-I/home/viktor/.cache/physics-relation-20261005/deps/_deps/json-src/include',str(H/'replay.cpp'),'-o',str(exe),str(base/'BulletDynamics/libBulletDynamics.a'),str(base/'BulletCollision/libBulletCollision.a'),str(base/'LinearMath/libLinearMath.a'),'/usr/lib/x86_64-linux-gnu/liblapack.so.3','/usr/lib/x86_64-linux-gnu/libblas.so.3'];r=subprocess.run(command,capture_output=True,text=True);(D/'compile.stdout').write_text(r.stdout);(D/'compile.stderr').write_text(r.stderr);save(D/'compile.json',{'command':command,'exit':r.returncode});r.check_returncode();exe_sha=sha(exe)
fn=next(n for n in ast.parse((ROOT/'research/new-combined-contact-review/run-20261005T194211Z/run23.py').read_text()).body if isinstance(n,ast.FunctionDef) and n.name=='external');ns={'np':np};exec(compile(ast.Module(body=[fn],type_ignores=[]),'independent','exec'),ns);records=[]
for i,(path,digest) in enumerate(plan['inputs'].items()):
 inp=ROOT/path;assert sha(inp)==digest;d=json.loads(inp.read_text());start=time.perf_counter();r=subprocess.run([str(exe),str(inp)],capture_output=True,text=True);(D/f'{i}.stdout.json').write_text(r.stdout);(D/f'{i}.stderr').write_text(r.stderr);o=json.loads(r.stdout);gate=ns['external'](d,o);assert not o['accepted'] or gate['accepted'];records.append({'input':path,'sha256':digest,'native_exit':r.returncode,'accepted':bool(o['accepted'] and gate['accepted'] and r.returncode==0),'independent':gate,'policy':o['null_traction_seed_policy'],'elapsed_s_descriptive':time.perf_counter()-start});save(D/'progress.json',records);print(i,len(d['b']),'accepted',records[-1]['accepted'],'largest',o['null_traction_seed_policy']['largest_component_rows'],'residual',gate['projection_m_s'],flush=True)
assert sha(exe)==exe_sha;save(D/'summary.json',{'complete':True,'source':subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),'binary_sha256':exe_sha,'records':records,'scope':'Original contact-law instantaneous proof only, no production/world/performance acceptance.'})
