"""Native finite-difference pilots with independent all-original-law acceptance."""
import ast,hashlib,json,os,subprocess,time
from pathlib import Path
import numpy as np
H=Path(__file__).resolve().parent;ROOT=H.parents[1];plan=json.loads((H/'plan.json').read_text());D=H/'results-v2';D.mkdir(exist_ok=False)
def save(p,x):p.write_text(json.dumps(x,indent=2,allow_nan=False)+'\n')
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert sha(H/'replay.cpp')==plan['source_sha256'] and sha(ROOT/plan['seed_archive'])==plan['seed_archive_sha256'];assert os.environ['OMP_NUM_THREADS']=='1' and os.environ['OPENBLAS_NUM_THREADS']=='1'
exe=Path(plan['binary']);exe.parent.mkdir(exist_ok=False);base=ROOT/'build/spatial/_deps/bullet-build/src';libs=[base/'BulletDynamics/libBulletDynamics.a',base/'BulletCollision/libBulletCollision.a',base/'LinearMath/libLinearMath.a'];command=['c++','-O3','-DNDEBUG','-DBT_USE_DOUBLE_PRECISION','-ffp-contract=off','-I'+str(ROOT/'spatial_backend'),'-I/home/viktor/.cache/physics-relation-20261005/deps/_deps/bullet-src/src','-I/home/viktor/.cache/physics-relation-20261005/deps/_deps/json-src/include',str(H/'replay.cpp'),'-o',str(exe),*[str(p) for p in libs],'-lcminpack'];r=subprocess.run(command,capture_output=True,text=True);(D/'compile.stdout').write_text(r.stdout);(D/'compile.stderr').write_text(r.stderr);save(D/'compile.json',{'command':command,'exit':r.returncode});r.check_returncode();exe_sha=sha(exe)
fn=next(n for n in ast.parse((ROOT/'research/new-combined-contact-review/run-20261005T194211Z/run23.py').read_text()).body if isinstance(n,ast.FunctionDef) and n.name=='external');ns={'np':np};exec(compile(ast.Module(body=[fn],type_ignores=[]),'independent','exec'),ns);records=[]
prior=json.loads((ROOT/plan['seed_archive']).read_text())
for index,old in enumerate(prior['records']):
 raw=ROOT/old['input'];assert sha(raw)==old['sha256'];d=json.loads(raw.read_text());globalp=np.array(d['p']);seen=set();recovered=False
 for attempt in old['attempts']:
  if attempt['seed'] in seen:continue
  seen.add(attempt['seed']);ids=attempt['original_rows'];inverse={k:i for i,k in enumerate(ids)};local=dict(A=np.array(d['A'])[np.ix_(ids,ids)].tolist(),b=np.array(d['b'])[ids].tolist(),p=attempt['seed_p'],lo=np.array(d['lo'])[ids].tolist(),hi=np.array(d['hi'])[ids].tolist(),dependencies=[inverse[k] if k>=0 else -1 for k in np.array(d['dependencies'])[ids]],tolerance_m_s=d['tolerance_m_s']);prefix=D/f'{index}-{attempt["seed"]}';inp=prefix.with_suffix('.input.json');save(inp,local);start=time.perf_counter();r=subprocess.run([str(exe),str(inp)],capture_output=True,text=True);prefix.with_suffix('.stdout.json').write_text(r.stdout);prefix.with_suffix('.stderr').write_text(r.stderr);o=json.loads(r.stdout);assert o['raw_evaluations']<=2048;gate=ns['external'](local,{'p':o['p'],'w':(np.array(local['A'])@o['p']-local['b']).tolist()});assert not o['accepted'] or gate['accepted'];record={'input':old['input'],'seed':attempt['seed'],'original_rows':ids,'native_exit':r.returncode,'native_accepted':o['accepted'],'independent':gate,'raw_evaluations':o['raw_evaluations'],'elapsed_s_descriptive':time.perf_counter()-start};records.append(record);save(D/'progress.json',records);print(index,attempt['seed'],'accepted',o['accepted'],'residual',gate['projection_m_s'],flush=True)
  if o['accepted']:globalp[ids]=o['p'];recovered=True;break
 candidate=D/f'{index}-candidate.json';save(candidate,dict(d,p=globalp.tolist()));native=subprocess.run([str(ROOT/'build/spatial/spatial_coulomb_replay'),str(candidate),'0'],capture_output=True,text=True);(D/f'{index}-production.json').write_text(native.stdout);globalgate=ns['external'](d,{'p':globalp.tolist(),'w':(np.array(d['A'])@globalp-d['b']).tolist()});save(D/f'{index}-summary.json',{'search_found':recovered,'production_zero_accepted':native.returncode==0,'independent':globalgate,'input':old['input']})
assert sha(exe)==exe_sha;save(D/'summary.json',{'complete':True,'source':subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),'binary_sha256':exe_sha,'records':records,'scope':'Instantaneous numerical search only; no production integration/world/reference/performance claim.'})
